### ISSUE TITLE
Refactor: Update Robot Status

### ISSUE THREAD

**Issue by lnalice** [lnalice/simple-robot-scene-manager#10]
**[[ branch ]]**
feature/robot-status

**[[ target files ]]**
feature/user-request와 겹치지 않는 파일들
- src/scene_manager/src/helper/moduleCalculator.py
- src/scene_manager/src/state_machines/control/control_module.py
- src/scene_manager/src/state_machines/move/move_together.py

**[[ problem ]]**
- 로봇 상태 업데이트하는 코드 전체 로직 확인 필요
- db에 적절한 값 저장되지 않음

**[[ to-do ]]**
- [x] 로봇 상태 업데이트: 모듈 단계 (degZ, degX아닌, module State) 반영
- [x] 로봇 상태 업데이트: 로봇상태 (IDLE, MOVE, MODULE ..)
- [x] 로봇 상태 업데이트: displacement 계산없이 linX, angZ, seconds로 반영 (향후 navigation도입 시 x,y,r로 변경)
